#ifndef __FFUN_CONFIG__
#define __FFUN_CONFIG__

#define FFUN_UDP_DGRAM_MAX_SIZE 508
#define FFUN_REQUESTED_DATA_SIZE 450
#define FFUN_REQUESTED_ELEMENTS_NUMBER 10
#define FFUN_REQUESTED_DATA_TIMEOUT -1

#define FFUN_FLAC_DATA_BUFF_CAPACITY 10
#define FFUN_RAW_DATA_BUFF_CAPACITY 10
#define FFUN_FLAC_DATA_BUFF_ELEMENT_SIZE 8192

#define FFUN_LOG_LEVEL_ENABLED_DEBUG
#define FFUN_LOG_LEVEL_ENABLED_VERBOSE

#endif
